

TXT = {
    "DE": {
        "title": "Deutschland-Netzkarte",
        "slider_wind": "Wind [% der SMARD-Orientierung]",
        "btn_save": "Speichern & Berechnen",
        "status_ok": "Szenario bewältigt.",
        "Wind_node_chosen" : "Du bearbeitest den Wind-Knoten mit der ID:{}",
        "load_node_chosen": "Du bearbeitest den Last-Knoten mit der ID:{}",
        "lokal_slider_wind": "Lokale Wind-Erzeugung [%]",
        "lokal_slider_load":"Lokale Energie verbrauch[%]",
        "Speicher_Knopf_wind": "Speichern & Berechnen",
        "Abbruch_Knopf_wind": "Abbrechen",
        "Stellgrößen": "Stellgrößen",
        "Seitentitel": "Deutschland-Netzkarte: SMARD + DC-Lastfluss",
        "neu_hier_txt": "👋 Neu im Simulator? Lerne die Grundlagen der Netzbalance in unserem Tutorial.",
        "Tutorial_Knopf": "Zum Tutorial",
        "Website_Title": "Deutschland-Netzkarte: SMARD-API, regelbare Restleistung und DC-Lastfluss",
        "Website_Untertitel": "SMARD wird nur für Netzlast, Wind und PV genutzt. Externe Importe/Exporte und SMARD-Restkategorien werden nicht geladen. Die restlichen Erzeuger werden künstlich als konventionelle Erzeuger netzstützend modelliert.",
        "Sprache": "Sprache",
        "Aufgabe": "Aufgabe",
        "Datenquelle": "Datenquelle",
        "SMARD_Datum": "SMARD-Datum",
        "help_Tag": "Sehr aktuelle Tage können noch unvollständige SMARD-Daten haben.",
        "wind_slider":"Wind [% der SMARD-Werte]",
        "pv_slider": "PV [% der SMARD-Werte]",
        "batterie_slider":"BESS Leistung/Energie [%]",
        "soc_slider":"BESS Start-SOC [%]",
        "titel_EE":"Netzmaßnahmen",
        "slider_Netz":"Leitungskapazität / Netzausbau [%]",
        "Szenario_bewaeltigt" : "Szenario bewältigt.",
        "Szenario_nicht_bewältigt" : "Szenario noch nicht bewältigt.",
        "24h_EE_Anteil":"24h EE-Anteil [%]",
        "max_Auslastung_24h":"max. Auslastung 24h [%]",
        "Stunden_Überlast" : "Stunden mit Überlast",
        "Warnung_GPS_ueberlast":"Der Grid Performance Score wurde stark reduziert, weil im Tagesverlauf mindestens eine Leitung über 100 % ausgelastet ist.",
        "Guter_GPS" : "Hoher Grid Performance Score: hoher EE-Anteil ohne Leitungsüberlast.",
        "Mittel_GPS":"Mittlerer Grid Performance Score: technisch brauchbar, aber EE-Anteil oder Netzbelastung sind nicht optimal.",
        "Niedrig_GPS":"Niedriger Grid Performance Score: geringe technische Güte durch niedrigen EE-Anteil oder Netzüberlast.",
        "Netzkarte" : "Netzkarte",
        "Stunde_des_Tages":"Stunde des Tages",
        "Leitungsauslastung" : "Leitungsauslastung",
        "Dispatch" : "Dispatch: (teilweise skalierte) SMARD-Last/Wind/PV + künstlich geregelte restliche Erzeuger",
        "Modellannahmen" : "Modellannahmen",
        "Zielgroeße":"- Zielgröße ist die SMARD-Netzlast.\n",
        "Windgroeße":"- Wind = SMARD Wind Offshore + Wind Onshore.\n",
        "PVgroeße":"- PV = SMARD Photovoltaik.\n",
        "konvgroeße":"- Restliche Erzeuger werden nicht aus SMARD geladen, sondern künstlich auf die Residuallast gefahren.\n",
        "Extgroeßen":"- Externe Importe, Exporte und kommerzielle Austauschflüsse werden nicht geladen.\n",
        "BESSgroeßen":"- BESS: positiv = Entladung, negativ = Ladung.\n",
        "Leitunggroeßen":"- Leitungsauslastung: DC-Loadflow-Näherung, kein vollständiger AC-Lastfluss.",
        "Weitere_Kennzahlen":"Weitere Kennzahlen",
        "Live_Kennzahlen" :"Live-Kennzahlen",
        "LK_Last":"Last [GW]",
        "LK_Wind":"Wind [GW]",
        "LK_PV":"PV [GW]",
        "LK_Konv":"Konv. Erz. [GW]",
        "LK_Bat":"BESS [GW]",
        "LK_SOC":"SOC [%]",
        "LK_Abregelung":"Abregelung",
        "Stündliche_Tabelle":"Stündliche Tabelle",
        "SMARD_API_Abrufe":"SMARD-API Abfragen",
        "Fehler_API":"FEHLER: Keine API-Metadaten",
        "PyPSA_Erzeuger_Speicher":"Erzeuger / Speicher",
        "Verbraucher_Cluster":"Verbraucher-Cluster",
        "PyPSA_Leitung":"PyPSA-Leitungen und DC-Lastfluss",
        "DC_Saldo_Winkel":"DC-Knotensalden und Winkel",
        "Kein_Saldo":"Keine Knotensalden verfügbar.",
    },
    "EN": {
        "title": "Germany Grid Map",
        "slider_wind": "Wind [% of SMARD reference]",
        "btn_save": "Save & Calculate",
        "status_ok": "Scenario solved.",
        "Wind_node_chosen" : "You are currently changing the wind node having ID:{}",
        "load_node_chosen": "You are currently changing the load node having ID:{}",
        "lokal_slider_wind": "Lokal wind energy generation[%]",
        "lokal_slider_load":"Lokal energy consumption[%]",
        "Speicher_Knopf_wind": "Save & Calculate",
        "Abbruch_Knopf_wind": "Abort",
        "Stellgrößen": "Adjustable values",
        "Seitentitel": "German grid map: SMARD + DC-Loadflow",
        "neu_hier_txt": "👋 First time in this Simulator? Learn the basics of grid balance in our tutorial.",
        "Tutorial_Knopf": "Go to the tutorial",
        "Website_Title": "German grid map: SMARD-API, adjustable konventional power and DC-Loadflow",
        "Website_Untertitel": "SMARD is just used for the load, wind and PV. Extern Imports/Exports and remaining SMARD-kategories are not used. The remaining power plants are artificially modelled as conventionel power plants which support the network",
        "Sprache": "Language",
        "Aufgabe": "Exercise",
        "Datenquelle": "Data source",
        "SMARD_Datum": "SMARD-Date",
        "help_Tag": "Data for very recent days may still be incomplete in SMARD.",
        "wind_slider":"wind [% of the SMARD-Value]",
        "pv_slider": "PV [% of the SMARD-Value]",
        "batterie_slider":"BESS Power/Energiy [%]",
        "soc_slider":"BESS start-SOC [%]",
        "titel_EE":"Grid measures",
        "slider_Netz":"Conductor capacity / grid expansion [%]",
        "Szenario_bewaeltigt" : "Scenario Completed.",
        "Szenario_nicht_bewältigt" : "Scenario not yet resolved.",
        "24h_EE_Anteil":"24h RE-share [%]",
        "max_Auslastung_24h":"max. utilization 24h [%]",
        "Stunden_Überlast" : "Hours with overload",
        "Warnung_GPS_ueberlast":"The Grid Performance Score has been significantly reduced because at least one line is operating at over 100% capacity at some point during the day.",
        "Guter_GPS" : "High Grid Performance Score: high share of renewable energy without overloading the grid.",
        "Mittel_GPS":"Average Grid Performance Score: technically acceptable, but the share of renewable energy or grid load is not optimal.",
        "Niedrig_GPS":"Low Grid Performance Score: poor technical quality due to a low share of renewable energy or grid overload.",
        "Netzkarte" : "Grid Map",
        "Stunde_des_Tages":"Time of Day",
        "Leitungsauslastung" : "Line Utilization",
        "Dispatch" : "Dispatch: (partially scaled) SMARD load/wind/PV + artificially controlled remaining generators",
        "Modellannahmen" : "Model Assumptions",
        "Zielgroeße":"- The target value is the SMARD grid load.\n",
        "Windgroeße":"- Wind = SMARD Wind Offshore + Wind Onshore.\n",
        "PVgroeße":"- PV = SMARD Photovoltaics.\n",
        "konvgroeße":"- The remaining generators are not loaded from SMARD but are manually set to the residual load.\n",
        "Extgroeßen":"- External imports, exports, and commercial trade flows are not loaded.\n",
        "BESSgroeßen":"- BESS: positive = discharge, negative = charge.\n",
        "Leitunggroeßen":"- Line load: DC load flow approximation; no full AC load flow.",
        "Weitere_Kennzahlen":"Additional Key Figures",
        "Live_Kennzahlen" :"Live Metrics",
        "LK_Last":"Load [GW]",
        "LK_Wind":"Wind [GW]",
        "LK_PV":"PV [GW]",
        "LK_Konv":"Conv. power plants [GW]",
        "LK_Bat":"BESS [GW]",
        "LK_SOC":"SOC [%]",
        "LK_Abregelung":"Curtailment",
        "Stündliche_Tabelle":"Hourly table",
        "SMARD_API_Abrufe":"SMARD API Queries",
        "Fehler_API":"ERROR: No API metadata",
        "PyPSA_Erzeuger_Speicher":"Generator / Storage Facility",
        "Verbraucher_Cluster":"Consumer load cluster",
        "PyPSA_Leitung":"PyPSA Lines and DC Load Flow",
        "DC_Saldo_Winkel":"DC Node Balances and Angles",
        "Kein_Saldo":"No node balances available.",
        
    }
}

TXT_Tut = {
    "DE": {
        "Tut_Sprache" : "Sprache",
        "Tut_Title": "📘 Tutorial: Das deutsche Stromnetz gestalten",
        "Tut_Intro": "In diesem Tutorial lernst du Schritt für Schritt, wie du den Simulator bedienst, Netzengpässe erkennst und den Anteil erneuerbarer Energien erhöhst.",
        "Tut_Goal": "Das Ziel ist nicht, einfach alle Slider auf den höchsten Wert zu stellen. Gesucht wird eine technisch sinnvolle Lösung mit hohem EE-Anteil, sicheren Leitungen und möglichst begrenztem Ausbau.",
        "Nav_Sim": "Simulator öffnen",
        "Nav_Model": "Modellgrundlagen",
        "Step1_Header": "Schritt 1: Szenario und Daten auswählen",
        "Step1_Text": "Öffne den Simulator und betrachte zunächst die Seitenleiste.\n\n1. Wähle unter **Aufgabe** ein Szenario oder den Sandboxmodus aus.\n2. Wenn du in der Sandbox Aufgabe bist, wähle ein Datum, für das du SMARD Daten möchtest. In den Szenarios ist das Datum vorgegeben.",
        "Step1_Expander_Title": "Was bedeuten diese Einstellungen?",
        "Step1_Expander_Text": "**Aufgabe**\n\nBestimmt die Ausgangssituation und die Bedingungen, die für eine erfolgreiche Lösung erfüllt werden müssen. Hier kannst du auch in den Sandboxmodus wechseln.\n\n**SMARD-Datum**\n\nBestimmt, welcher Tag simuliert wird. Wind, Sonne und Stromverbrauch können sich von Tag zu Tag stark unterscheiden.",
        "Step2_Header": "Schritt 2: Den Ausgangszustand untersuchen",
        "Step2_Text": "Verändere zunächst noch keinen Slider. Betrachte die Kennzahlen im Bereich **24h Grid Performance Score**.",
        "Step2_Score": "### Grid Performance Score\n\nIst eine errechnete Gesamtbewertung deiner Lösung.\n\nEin hoher Wert bedeutet grundsätzlich:\n\n- hoher Anteil erneuerbarer Energien,\n- keine Netzüberlastung,\n- wenig Abschaltung von erneuerbaren Erzeugern. (also kein unnötig großer Ausbau)",
        "Step2_EE": "### 24h EE-Anteil [%]\n\nZeigt, welcher Anteil des Tagesverbrauchs durch Wind, PV und nutzbare Batterieentladung gedeckt wird.",
        "Step2_MaxLine": "### Max. Leitung 24h [%]\n\nDie höchste Leitungsauslastung, die während des gesamten Tages auftritt. Mehr als 100 % auslastung ist nicht zulässig und verschlechtert den Grid Performancescore stark.",
        "Step2_Overload": "### Stunden mit Überlast\n\nAnzahl der Stunden, in denen mindestens eine Leitung über 100 % ausgelastet ist.\n\nEin Zielwert von **0 Stunden** bedeutet, dass während des gesamten Tages keine modellierte Leitungsgrenze überschritten wird.",
        "Step3_Header": "Schritt 3: Eine einzelne Stunde untersuchen",
        "Step3_Text": "Nutze den Slider **Stunde des Tages**, um verschiedene Stunden zwischen 0 und 23 Uhr auszuwählen.\n\nUntersuche stichprobenartig:\n\n- eine Nachtstunde,\n- eine Mittagsstunde,\n- eine Abendstunde.",
        "Step3_Subheader": "Stunde des Tages",
        "Step3_SliderText": "Der Stundenslider verändert nichts an der Simulation. Er wählt lediglich die Stunde aus, die auf der Netzkarte, im Leitungsdiagramm und in den Live-Kennzahlen genauer dargestellt wird.",
        "Step3_Observe": "Beim Verschieben des Reglers solltest du beobachten:\n\n1. Wie hoch ist der Anteil der Photovoltaikerzeugung?\n2. Wie hoch ist der Anteil der Winderzeugung?\n3. Wie hoch ist die maximale Leitungsauslastung?\n4. Lädt oder entlädt der Batteriespeicher?",
        "Step4_Header": "Schritt 4: Wind- und PV-Ausbau testen",
        "Tab_Wind": "Wind",
        "Tab_PV": "Photovoltaik",
        "Step4_Wind_Subheader": "Wind [%]",
        "Step4_Wind_Text": "Dieser Slider skaliert die gesamte Windstromerzeugung des ausgewählten Tages. Wind an Land und Wind auf See werden gemeinsam verändert.",
        "Step4_Wind_Bullets": "- **0 %:** keine Windstromerzeugung\n- **100 %:** reale Windstromerzeugung\n- **150 %:** 50 % mehr Windstrom\n- **200 %:** doppelte Windstromerzeugung\n- **300 %:** dreifache Windstromerzeugung",
        "Step4_Wind_Experiment": "**Experiment**\n\n1. Erhöhe Wind um 25 oder 50 Prozentpunkte.\n2. Betrachte den neuen EE-Anteil.\n3. Prüfe die maximale Leitungsauslastung. Wenn eine Leitung aufgrund von erhöhter Windstromerzeugung überlastet ist, kannst du auf das Wind Symbol in der Netzkarte klicken und nur für diesen Knoten die Erzeugung wieder senken.\n4. Untersuche ob der Grid Performance Score gestiegen oder gesunken ist.",
        "Step4_Wind_Info": "Mehr Windenergie erhöht häufig den EE-Anteil. Gleichzeitig muss die zusätzliche Energie von den windreichen Regionen zu den Verbrauchern transportiert werden.",
        "Step4_PV_Subheader": "PV [%]",
        "Step4_PV_Text": "Dieser Slider skaliert die Photovoltaikerzeugung des ausgewählten Tages.",
        "Step4_PV_Bullets": "- **0 %:** keine Photovoltaikerzeugung\n- **100 %:** reale Photovoltaikerzeugung\n- **150 %:** 50 % mehr Photovoltaik\n- **200 %:** doppelte Photovoltaikerzeugung\n- **300 %:** dreifache Photovoltaikerzeugung",
        "Step4_PV_Experiment": "**Experiment**\n\n1. Stelle Wind zunächst wieder auf den Ausgangswert.\n2. Erhöhe PV um 25 oder 50 Prozentpunkte.\n3. Betrachte besonders die Mittagsstunden.\n4. Prüfe, ob der Batteriespeicher lädt.\n5. Achte auf Überschüsse oder Abregelung.",
        "Step4_PV_Info": "PV erzeugt hauptsächlich tagsüber Strom. Ein sehr hoher PV-Ausbau kann deshalb mittags Überschüsse erzeugen, obwohl nachts weiterhin zusätzliche Erzeugung benötigt wird.",
        "Step5_Header": "Schritt 5: Batteriespeicher einsetzen",
        "Step5_BessPower": "BESS Leistung/Energie [%]",
        "Step5_BessPower_Text": "BESS bedeutet Battery Energy Storage System. Der Slider skaliert im Simulator gleichzeitig die Lade- und Entladeleistung sowie die verfügbare Speicherkapazität.",
        "Step5_BessPower_Bullets": "- **0 %:** kein Batteriespeicher\n- **100 %:** Referenzgröße\n- **200 %:** doppelte Leistung und Speicherkapazität\n- **500 %:** fünffache Leistung und Speicherkapazität",
        "Step5_BessSOC": "BESS Start-SOC [%]",
        "Step5_BessSOC_Text": "SOC bedeutet State of Charge und beschreibt den Ladezustand des Speichers zu Beginn des Tages.",
        "Step5_BessSOC_Bullets": "- **0 %:** Speicher vollständig leer\n- **50 %:** Speicher zur Hälfte geladen\n- **100 %:** Speicher vollständig geladen",
        "Step5_Experiment": "**Experiment**\n\n1. Erzeuge durch einen höheren Wind- oder PV-Wert zeitweise einen Überschuss.\n2. Vergleiche die Bilanz vor und nach BESS.\n3. Erhöhe anschließend die BESS-Größe.\n4. Prüfe, ob mehr Überschuss aufgenommen werden kann.\n5. Beobachte den SOC im Tagesverlauf.",
        "Step5_Info": "Ein großer Speicher kann die Bilanz verbessern, erhöht aber auch den die Kosten eines Systems. Mehr Speicher ist daher nicht automatisch die beste Lösung.",
        "Step6_Header": "Schritt 6: Einen Netzengpass beheben",
        "Step6_Grid_Subheader": "Leitungskapazität / Netzausbau [%]",
        "Step6_Grid_Text": "Dieser Slider skaliert die Kapazität aller modellierten Leitungen. Er stellt einen vereinfachten Ausbau des gesamten Übertragungsnetzes dar.",
        "Step6_Grid_Bullets": "- **50 %:** halbe Leitungskapazität\n- **100 %:** ursprüngliche Leitungskapazität\n- **200 %:** doppelte Leitungskapazität",
        "Step6_Experiment": "**Experiment**\n\n1. Erzeuge zunächst durch mehr Wind oder PV eine Leitungsüberlastung.\n2. Erhöhe den Netzausbau in kleinen Schritten und senke Windstromerzeugung an kritischen Knoten.\n3. Stoppe, sobald die Leitungsauslastung ausreichend reduziert wurde.\n4. Prüfe ob der Grid Performance Score gestiegen oder gefallen ist.",
        "Step6_Info": "Verändere den Netzausbau möglichst in kleinen Schritten. Ein unnötig hoher Ausbau kann den Grid Performance Score trotz sicherer Leitungen verschlechtern.",
        "Step6_Caption": "In der Realität würden einzelne Leitungen gezielt ausgebaut. Der globale Slider ist eine didaktische Vereinfachung.",
        "Step7_Header": "Schritt 7: Eine eigene Lösung optimieren",
        "Step7_Text": "Versuche nun, das ausgewählte Szenario vollständig zu lösen.\n\nGehe dabei iterativ vor:\n\n1. Erhöhe Wind oder PV nur in kleinen Schritten.\n2. Prüfe nach jeder Änderung den 24h-EE-Anteil.\n3. Kontrolliere die maximale Leitungsauslastung.\n4. Nutze Speicher für zeitliche Überschüsse.\n5. Baue das Netz nur so weit aus wie erforderlich.\n6. Vergleiche nach jeder Änderung den Grid Performance Score.",
        "Goal1": "Ziel 1",
        "Goal1_Val": "Hoher EE-Anteil",
        "Goal1_Help": "Wind, PV und Speicher sollen möglichst viel Last decken.",
        "Goal2": "Ziel 2",
        "Goal2_Val": "Sicherheit",
        "Goal2_Help": "Keine Überlastung: Leitungen sollen während des gesamten Tages unter 100 % bleiben.",
        "Goal3": "Ziel 3",
        "Goal3_Val": "Effizienz",
        "Goal3_Help": "Es sollte möglichst effizient ausgebaut werden, also möglichst wenig Erneuerbare Überproduktion welche zu Abregelung führt.",
        "Warning_NoData": "Die Daten wurden noch nicht berechnet. Du wirst zur Hauptseite weitergeleitet...",
        "Charts_Header": "Was zeigen die Diagramme?",
        "Tab_Map": "Netzkarte",
        "Tab_Line": "Leitungsauslastung der aktuellen Stunde",
        "Tab_Line_Max": "Maximale Leitungsauslastung des Tages",
        "Tab_Dispatch": "Erzeugungsmix",
        "Chart_Map_Sub": "Netzkarte",
        "Chart_Map_Text1": "Die Netzkarte zeigt Erzeuger, Verbraucher, Batteriespeicher und Leitungen für die ausgewählte Stunde.",
        "Chart_Map_Colors": "**Leitungsfarben**\n\n- 🟢 Grün: weniger als 90 % ausgelastet\n- 🟠 Orange: mindestens 90 %, aber nicht über 100 %\n- 🔴 Rot: über 100 % ausgelastet",
        "Chart_Map_Symbols": "**Symbole**\n\n- Dreieck: Wind\n- Quadrat: Photovoltaik\n- Raute: Batteriespeicher\n- Kreis: restliche regelbare Erzeugung\n- Stern: Verbrauchercluster",
        "Chart_Map_Text2": "Die Größe der Symbole hängt von der aktuellen Erzeugung oder dem aktuellen Verbrauch ab.",
        "Chart_Map_Info": "Bewege den Mauszeiger über eine Leitung, um Kapazität, Leistungsfluss und prozentuale Auslastung anzuzeigen. Auf das Windsymbol kannst du klicken und die Generation an dem gewählten Knoten reduzieren.",
        "Chart_Line_Sub": "Leitungsauslastung",
        "Chart_Line_Text1": "Das Balkendiagramm zeigt die Auslastung aller Leitungen in der ausgewählten Stunde.",
        "Chart_Line_Bullets": "- Die Balken sind nach Auslastung sortiert.\n- Die rote gestrichelte Linie markiert 100 %.\n- Der höchste Balken zeigt den aktuell größten Netzengpass.",
        "Chart_Line_Info": "Ein Wert über 100 % bedeutet, dass der berechnete Leistungsfluss größer als die im Modell verfügbare Leitungskapazität ist.",
        "Chart_LineMax_Sub": "Maximale Leitungsauslastung",
        "Chart_LineMax_Text": "Das Balkendiagramm zeigt die maximale Leitungsauslastung jeder Stunde des Tages.",
        "Chart_Dispatch_Sub": "Dispatch und Erzeugungsmix",
        "Chart_Dispatch_Text1": "Das Diagramm zeigt für jede Stunde, durch welche Technologien der Stromverbrauch gedeckt wird.",
        "Chart_Dispatch_Bullets": "**Positive Balken**\n\n- Wind\n- Photovoltaik\n- restliche regelbare Erzeuger\n- BESS-Entladung\n\n**Negative Balken**\n\n- BESS-Ladung\n- Abregelung erneuerbarer Energie\n\n**Schwarze Linie**\n\nStromverbrauch beziehungsweise Ziel-Last.\n\n**Gepunktete graue Linie**\n\nRechnerisch benötigte restliche Erzeugung vor Berücksichtigung der Limits.",
        "Metrics_Header": "Weitere Kennzahlen",
        "Metrics_Expander": "Kennzahlen der ausgewählten Stunde",
        "Metrics_Text": "**Last[GW]** \nStromverbrauch in der ausgewählten Stunde.\n\n**Wind [GW] und PV [GW]** \nAktuelle erneuerbare Erzeugungsleistung.\n\n**Konv. Erz. [GW]** \nAktuell eingesetzte regelbare restliche Erzeugung.\n\n**BESS [GW]** \nPositiv bedeutet Entladung, negativ bedeutet Ladung.\n\n**Ziellücke nach EE** \nLast abzüglich Wind- und PV-Erzeugung.\n\n**Restl. verfügbar [GW]** \nMaximal verfügbare Leistung der restlichen Erzeuger.\n\n**Ziellücke vor BESS** \nVerbleibende Differenz vor dem Einsatz des Batteriespeichers.\n\n**SOC [%]** \nAktueller Ladezustand des Batteriespeichers.\n\n**Abregelung** \nErneuerbare Erzeugung, die nicht verwendet werden kann.\n",
        "Footer_Back": "Zurück zum Simulator",
        "Page_Title": "Tutorial"
    },
    "EN": {
        "Tut_Sprache" : "Language",
        "Tut_Title": "📘 Tutorial: Designing the German Power Grid",
        "Tut_Intro": "In this tutorial, you will learn step-by-step how to use the simulator, identify grid bottlenecks, and increase the share of renewable energies.",
        "Tut_Goal": "The goal is not to simply set all sliders to the highest value. We are looking for a technically sound solution with a high RE share, secure power lines, and the least possible grid expansion.",
        "Nav_Sim": "Open Simulator",
        "Nav_Model": "Model Fundamentals",
        "Step1_Header": "Step 1: Select Scenario and Data",
        "Step1_Text": "Open the simulator and look at the sidebar first.\n\n1. Select a scenario or the sandbox mode under **Task**.\n2. If you are in the sandbox task, select a date for which you want SMARD data. In the scenarios, the date is predetermined.",
        "Step1_Expander_Title": "What do these settings mean?",
        "Step1_Expander_Text": "**Task**\n\nDetermines the starting situation and the conditions that must be met for a successful solution. Here you can also switch to sandbox mode.\n\n**SMARD Date**\n\nDetermines which day is simulated. Wind, sun, and power consumption can vary greatly from day to day.",
        "Step2_Header": "Step 2: Examine the Initial State",
        "Step2_Text": "Do not change any slider yet. Look at the key figures in the **24h Grid Performance Score** section.",
        "Step2_Score": "### Grid Performance Score\n\nIs a calculated overall rating of your solution.\n\nA high value generally means:\n\n- high share of renewable energies,\n- no grid overload,\n- little curtailment of renewable generators. (meaning no unnecessarily large expansion)",
        "Step2_EE": "### 24h RE Share [%]\n\nShows what proportion of daily consumption is covered by wind, PV, and usable battery discharge.",
        "Step2_MaxLine": "### Max. Line 24h [%]\n\nThe highest line utilization that occurs during the entire day. More than 100% utilization is not permitted and severely worsens the Grid Performance Score.",
        "Step2_Overload": "### Hours with Overload\n\nNumber of hours in which at least one line is overloaded by more than 100%.\n\nA target value of **0 hours** means that no modeled line limit is exceeded during the entire day.",
        "Step3_Header": "Step 3: Examine a Single Hour",
        "Step3_Text": "Use the **Hour of the Day** slider to select different hours between 0 and 23 o'clock.\n\nExamine randomly:\n\n- a night hour,\n- a midday hour,\n- an evening hour.",
        "Step3_Subheader": "Hour of the Day",
        "Step3_SliderText": "The hour slider does not change anything in the simulation. It merely selects the hour that is shown in more detail on the grid map, in the line chart, and in the live metrics.",
        "Step3_Observe": "When moving the slider, you should observe:\n\n1. How high is the share of photovoltaic generation?\n2. How high is the share of wind generation?\n3. How high is the maximum line utilization?\n4. Is the battery storage charging or discharging?",
        "Step4_Header": "Step 4: Test Wind and PV Expansion",
        "Tab_Wind": "Wind",
        "Tab_PV": "Photovoltaics",
        "Step4_Wind_Subheader": "Wind [%]",
        "Step4_Wind_Text": "This slider scales the entire wind power generation of the selected day. Onshore and offshore wind are changed together.",
        "Step4_Wind_Bullets": "- **0 %:** no wind power generation\n- **100 %:** real wind power generation\n- **150 %:** 50 % more wind power\n- **200 %:** double wind power generation\n- **300 %:** triple wind power generation",
        "Step4_Wind_Experiment": "**Experiment**\n\n1. Increase wind by 25 or 50 percentage points.\n2. Look at the new RE share.\n3. Check the maximum line utilization. If a line is overloaded due to increased wind power generation, you can click on the wind symbol in the grid map and reduce the generation for this node only.\n4. Examine whether the Grid Performance Score has risen or fallen.",
        "Step4_Wind_Info": "More wind energy often increases the RE share. At the same time, the additional energy must be transported from the windy regions to the consumers.",
        "Step4_PV_Subheader": "PV [%]",
        "Step4_PV_Text": "This slider scales the photovoltaic generation of the selected day.",
        "Step4_PV_Bullets": "- **0 %:** no photovoltaic generation\n- **100 %:** real photovoltaic generation\n- **150 %:** 50 % more photovoltaics\n- **200 %:** double photovoltaic generation\n- **300 %:** triple photovoltaic generation",
        "Step4_PV_Experiment": "**Experiment**\n\n1. First set wind back to the initial value.\n2. Increase PV by 25 or 50 percentage points.\n3. Pay particular attention to the midday hours.\n4. Check if the battery storage is charging.\n5. Watch out for surpluses or curtailment.",
        "Step4_PV_Info": "PV generates electricity mainly during the day. A very high PV expansion can therefore create surpluses at noon, although additional generation is still needed at night.",
        "Step5_Header": "Step 5: Use Battery Storage",
        "Step5_BessPower": "BESS Power/Energy [%]",
        "Step5_BessPower_Text": "BESS stands for Battery Energy Storage System. The slider simultaneously scales the charging and discharging power as well as the available storage capacity in the simulator.",
        "Step5_BessPower_Bullets": "- **0 %:** no battery storage\n- **100 %:** reference size\n- **200 %:** double power and storage capacity\n- **500 %:** quintuple power and storage capacity",
        "Step5_BessSOC": "BESS Initial SOC [%]",
        "Step5_BessSOC_Text": "SOC stands for State of Charge and describes the charging state of the storage at the beginning of the day.",
        "Step5_BessSOC_Bullets": "- **0 %:** storage completely empty\n- **50 %:** storage half full\n- **100 %:** storage completely full",
        "Step5_Experiment": "**Experiment**\n\n1. Create a temporary surplus with a higher wind or PV value.\n2. Compare the balance before and after BESS.\n3. Then increase the BESS size.\n4. Check whether more surplus can be absorbed.\n5. Observe the SOC over the course of the day.",
        "Step5_Info": "A large storage facility can improve the balance, but also increases the costs of a system. More storage is therefore not automatically the best solution.",
        "Step6_Header": "Step 6: Resolve a Grid Bottleneck",
        "Step6_Grid_Subheader": "Line Capacity / Grid Expansion [%]",
        "Step6_Grid_Text": "This slider scales the capacity of all modeled lines. It represents a simplified expansion of the entire transmission grid.",
        "Step6_Grid_Bullets": "- **50 %:** half line capacity\n- **100 %:** original line capacity\n- **200 %:** double line capacity",
        "Step6_Experiment": "**Experiment**\n\n1. First create a line overload with more wind or PV.\n2. Increase the grid expansion in small steps and reduce wind power generation at critical nodes.\n3. Stop as soon as the line utilization is sufficiently reduced.\n4. Check whether the Grid Performance Score has risen or fallen.",
        "Step6_Info": "Change the grid expansion in small steps if possible. An unnecessarily high expansion can worsen the Grid Performance Score despite secure lines.",
        "Step6_Caption": "In reality, individual lines would be specifically expanded. The global slider is a didactic simplification.",
        "Step7_Header": "Step 7: Optimize Your Own Solution",
        "Step7_Text": "Now try to completely solve the selected scenario.\n\nProceed iteratively:\n\n1. Increase wind or PV only in small steps.\n2. Check the 24h RE share after each change.\n3. Check the maximum line utilization.\n4. Use storage for temporary surpluses.\n5. Expand the grid only as much as necessary.\n6. Compare the Grid Performance Score after each change.",
        "Goal1": "Goal 1",
        "Goal1_Val": "High RE Share",
        "Goal1_Help": "Wind, PV, and storage should cover as much load as possible.",
        "Goal2": "Goal 2",
        "Goal2_Val": "Security",
        "Goal2_Help": "No overload: Lines should stay below 100% during the entire day.",
        "Goal3": "Goal 3",
        "Goal3_Val": "Efficiency",
        "Goal3_Help": "Expansion should be as efficient as possible, meaning as little renewable overproduction leading to curtailment as possible.",
        "Warning_NoData": "The data has not yet been calculated. You will be redirected to the main page...",
        "Charts_Header": "What do the charts show?",
        "Tab_Map": "Grid Map",
        "Tab_Line": "Line utilization of the current hour",
        "Tab_Line_Max": "Maximum line utilization of the day",
        "Tab_Dispatch": "Generation Mix",
        "Chart_Map_Sub": "Grid Map",
        "Chart_Map_Text1": "The grid map shows generators, consumers, battery storage, and lines for the selected hour.",
        "Chart_Map_Colors": "**Line Colors**\n\n- 🟢 Green: less than 90 % utilized\n- 🟠 Orange: at least 90 %, but not over 100 %\n- 🔴 Red: over 100 % utilized",
        "Chart_Map_Symbols": "**Symbols**\n\n- Triangle: Wind\n- Square: Photovoltaics\n- Diamond: Battery storage\n- Circle: remaining dispatchable generation\n- Star: Consumer cluster",
        "Chart_Map_Text2": "The size of the symbols depends on the current generation or current consumption.",
        "Chart_Map_Info": "Hover over a line to display capacity, power flow, and percentage utilization. You can click on the wind symbol to reduce generation at the selected node.",
        "Chart_Line_Sub": "Line Utilization",
        "Chart_Line_Text1": "The bar chart shows the utilization of all lines in the selected hour.",
        "Chart_Line_Bullets": "- The bars are sorted by utilization.\n- The red dashed line marks 100 %.\n- The highest bar shows the currently largest grid bottleneck.",
        "Chart_Line_Info": "A value over 100 % means that the calculated power flow is greater than the line capacity available in the model.",
        "Chart_LineMax_Sub": "Maximum Line Utilization",
        "Chart_LineMax_Text": "The bar chart shows the maximum line utilization of every hour of the day.",
        "Chart_Dispatch_Sub": "Dispatch and Generation Mix",
        "Chart_Dispatch_Text1": "The chart shows for each hour which technologies are used to cover power consumption.",
        "Chart_Dispatch_Bullets": "**Positive Bars**\n\n- Wind\n- Photovoltaics\n- remaining dispatchable generators\n- BESS discharge\n\n**Negative Bars**\n\n- BESS charge\n- Curtailment of renewable energy\n\n**Black Line**\n\nPower consumption or target load.\n\n**Dotted Gray Line**\n\nMathematically required remaining generation before considering limits.",
        "Metrics_Header": "More Metrics",
        "Metrics_Expander": "Metrics of the selected hour",
        "Metrics_Text": "**Load [GW]** \nPower consumption in the selected hour.\n\n**Wind [GW] and PV [GW]** \nCurrent renewable generation capacity.\n\n**Conv. power plants [GW]** \nCurrently deployed dispatchable remaining generation.\n\n**BESS [GW]** \nPositive means discharge, negative means charge.\n\n**Target Gap after RE** \nLoad minus wind and PV generation.\n\n**Rem. available [GW]** \nMaximum available capacity of remaining generators.\n\n**Target Gap before BESS** \nRemaining difference before using the battery storage.\n\n**SOC [%]** \nCurrent state of charge of the battery storage.\n\n**Curtailment** \nRenewable generation that cannot be used.\n",
        "Footer_Back": "Back to Simulator",
        "Page_Title": "Tutorial"
    }
}

TXT_Abt = {
    "DE": {
        "Abt_Sprache": "Sprache",
        "Abt_Title": "About: Allgemeines zum Simulator",
        "Abt_Intro": "Auf dieser Seite findest du Hintergrundinformationen zum Stromnetzmodell, zu den verwendeten Daten und zur DC-Lastflussberechnung.",
        "Abt_Sec1_Title": "1. Was ist diese Website?",
        "Abt_Sec1_Text": "Diese Website ist ein interaktiver **Netzsimulator für Deutschland**. Sie nutzt reale Verbrauchs- und Erzeugungsdaten (von der SMARD-Plattform der Bundesnetzagentur) und verbindet sie mit einem vereinfachten Modell des deutschen Höchstspannungsnetzes. Du übernimmst die Rolle der Netzplanung und musst versuchen, das Stromnetz effektiv zu verändern, um den Anteil der erneuerbaren Energien im Energiemix zu erhöhen.",
        "Abt_Sec2_Title": "2. Was ist ein Übertragungsnetz?",
        "Abt_Sec2_Text": "Das Stromnetz besteht aus dem Übertragungsnetz und dem Verteilnetz. Das Übertragungsnetz ist dabei der Teil, der große Mengen Energie über weite Strecken bei Höchstspannung (220 kV und 380 kV) transportiert. Auch Hochspannungs-Gleichstromübertragung (HGÜ) zählt zum Übertragungsnetz, jedoch wird diese in dieser Simulation nicht separat betrachtet. Das Übertragungsnetz wird benötigt, da der Energiebedarf nicht immer an einem Ort selber gedeckt werden kann.",
        "Abt_Sec3_Title": "3. Welche Herausforderungen gibt es aktuell?",
        "Abt_Sec3_Text": "Die Energiewende stellt das Netz vor große Herausforderungen:\n* **Geografische Ungleichverteilung:** Die meiste Windenergie wird im Norden generiert, der Großteil der Industrie (und der höchste Energiebedarf) befindet sich jedoch im Süden. Zudem befindet sich die meiste solare Energiegewinnung im Süden des Landes und muss in Zeiten mit wenig Wind in den Norden transportiert werden.\n* **Wetterabhängigkeit:** Wind und Sonne liefern nicht konstant Strom. Da oft nur einer der Erzeuger gleichzeitig ausfällt, besteht an solchen Tagen hoher Transportbedarf.\n* **Netzengpässe (Bottlenecks):** Wenn zu viel Windstrom vom Norden in den Süden drängt, reichen die Kapazitäten des Übertragungsnetzes oft nicht aus. In solchen Fällen muss die Erzeugung abgeregelt werden und im Süden muss Energie auf andere, oft fossile Art gewonnen werden.",
        "Abt_Sec4_Title": "4. Was ist das Ziel dieser Simulation?",
        "Abt_Sec4_Info": "Deine Aufgabe ist es, den **Grid Performance Score** zu optimieren. Er bewertet, wie gut dein Stromnetz erneuerbare Energien nutzt, Leitungsüberlastungen vermeidet und den zusätzlichen Ausbau begrenzt.",
        "Abt_Sec4_Sub1": " Leitungen schützen",
        "Abt_Sec4_Text1": "Keine Leitung darf über 100 % ausgelastet sein, sonst drohen Stromausfälle.",
        "Abt_Sec4_Sub2": " Abregelung minimieren",
        "Abt_Sec4_Text2": "Verhindere, dass sauberer Wind- und Solarstrom weggeworfen (abgeregelt) werden muss, weil das Netz voll ist.",
        "Abt_Sec4_Sub3": " Nicht unnötig viel Ausbau",
        "Abt_Sec4_Text3": "Versuche dein Netz so effizient wie möglich zu bauen. Wenn du zu viele Kapazitäten hinzufügst, die gar nicht genutzt werden, sinkt die Effizienz deines Netzes.",
        "Abt_Sec5_Title": "5. Wie funktioniert die Lastflussrechnung?",
        "Abt_Sec5_Sub1": "### DC-Lastflussmodell",
        "Abt_Sec5_Text1": "Für die vereinfachte Berechnung des Leistungsflusses im Netz verwenden wir ein DC-Lastflussmodell. Dabei gelten folgende vereinfachende Annahmen:",
        "Abt_Sec5_List1": "**1. Spannungsbeträge sind näherungsweise konstant:**",
        "Abt_Sec5_List2": "**2. Leitungswiderstände werden gegenüber der Reaktanz vernachlässigt:**",
        "Abt_Sec5_List3": "**3. Die Winkeldifferenzen zwischen den Knoten sind klein:**",
        "Abt_Sec5_List4": "**4. Es wird nur Wirkleistung betrachtet.**",
        "Abt_Sec5_Sub2": "### Leistungsfluss zwischen zwei Knoten",
        "Abt_Sec5_Text2": "Unter diesen Annahmen kann der Wirkleistungsfluss auf einer Leitung zwischen den Knoten $a$ und $b$ näherungsweise berechnet werden als:",
        "Abt_Sec5_Text3": "Dabei sind $\\theta_a$ und $\\theta_b$ die Spannungswinkel der beiden Knoten und $x_{ab}$ die Leitungsreaktanz in Per Unit.",
        "Abt_Sec5_Text4": "Alternativ kann man mit dem Leitwertfaktor schreiben:",
        "Abt_Sec5_Sub3": "### Knotengleichung",
        "Abt_Sec5_Text5": "Für einen Knoten $m$ ergibt sich der gesamte Leistungsfluss aus der Summe der Leistungsflüsse zu allen angeschlossenen Nachbarknoten:",
        "Abt_Sec5_Text6": "Dabei bezeichnet $N(m)$ die Menge der Nachbarknoten von $m$. Die Gleichungen aller Knoten können anschließend als lineares Gleichungssystem in Matrixform geschrieben werden.",
        "Abt_Expander": "Beispielrechnung: DC-Lastfluss mit 3 Knoten",
        "Abt_Exp_Sub1": "### 1. Eingaben",
        "Abt_Exp_Text1": "Wir betrachten ein vereinfachtes Netz mit drei Knoten $i$, $j$ und $k$. Die Knoten $i$ und $j$ speisen Leistung ein, während Knoten $k$ Leistung aufnimmt.",
        "Abt_Exp_Caption": "Dreiknoten-Netz für die Beispielrechnung",
        "Abt_Exp_Text2": "Für die Per-Unit-Rechnung werden zunächst die Basisgrößen festgelegt:",
        "Abt_Exp_Text3": "Daraus ergibt sich die Basisimpedanz:",
        "Abt_Exp_Text4": "Die eingespeisten bzw. entnommenen Leistungen sind:",
        "Abt_Exp_Text5": "Das Netz ist ausgeglichen, weil gilt:",
        "Abt_Exp_Text6": "Die Leitungsreaktanzen betragen:",
        "Abt_Exp_Text7": "Diese werden mit der Basisimpedanz in Per Unit umgerechnet:",
        "Abt_Exp_Sub2": "### 2. Reduzierte Gleichung",
        "Abt_Exp_Text8": "Damit die Winkel eindeutig bestimmt werden können, wird ein Knoten als Referenzknoten gewählt. Hier setzen wir:",
        "Abt_Exp_Text9": "Die Knotengleichungen für die verbleibenden unbekannten Winkel $\\theta_i$ und $\\theta_j$ ergeben:",
        "Abt_Exp_Text10": "Die rechte Seite enthält dabei die eingespeiste bzw. entnommene Leistung in Per Unit.",
        "Abt_Exp_Text11": "Durch Lösen des linearen Gleichungssystems erhält man:",
        "Abt_Exp_Sub3": "### 3. Ergebnisse",
        "Abt_Exp_Text12": "Die Leistungsflüsse auf den Leitungen werden zunächst in Per Unit berechnet und anschließend in MW umgerechnet.",
        "Abt_Exp_Text13": "**Leitung von i nach j:**",
        "Abt_Exp_Text14": "**Leitung von i nach k:**",
        "Abt_Exp_Text15": "**Leitung von j nach k:**",
        "Abt_Exp_Text16": "Damit fließen insgesamt 800 MW zu Knoten $k$. Zusätzlich fließen 100 MW von Knoten $i$ nach Knoten $j$.",
        "Abt_Exp_Success": "Interpretation: Der Haupttransport erfolgt von den einspeisenden Knoten i und j zum Verbrauchsknoten k. Zusätzlich fließen 100 MW von i nach j, da die Knotenspannungswinkel unterschiedlich sind.",
        "Abt_End_Success": "Du kennst jetzt die wichtigsten Grundlagen des verwendeten Netzmodells.",
        "Abt_Link_Tut": "Zum interaktiven Tutorial",
        "Abt_Link_Sim": "Direkt zum Simulator"
    },
    "EN": {
        "Abt_Sprache": "Language",
        "Abt_Title": "About: General Information about the Simulator",
        "Abt_Intro": "On this page, you will find background information about the power grid model, the data used, and the DC load flow calculation.",
        "Abt_Sec1_Title": "1. What is this website?",
        "Abt_Sec1_Text": "This website is an interactive **grid simulator for Germany**. It uses real consumption and generation data (from the Federal Network Agency's SMARD platform) and combines it with a simplified model of the German extra-high voltage grid. You take on the role of grid planning and must try to effectively modify the power grid to increase the share of renewable energies in the energy mix.",
        "Abt_Sec2_Title": "2. What is a transmission grid?",
        "Abt_Sec2_Text": "The power grid consists of the transmission grid and the distribution grid. The transmission grid is the part that transports large amounts of energy over long distances at extra-high voltages (220 kV and 380 kV). High-voltage direct current (HVDC) transmission is also part of the transmission grid, but it is not considered separately in this simulation. The transmission grid is needed because the energy demand cannot always be met locally.",
        "Abt_Sec3_Title": "3. What are the current challenges?",
        "Abt_Sec3_Text": "The energy transition poses major challenges for the grid:\n* **Geographical uneven distribution:** Most wind energy is generated in the north, while the majority of industry (and the highest energy demand) is located in the south. In addition, most solar energy is generated in the south of the country and must be transported to the north during times of low wind.\n* **Weather dependency:** Wind and sun do not provide electricity constantly. Since often only one of the sources drops out at a time, there is a high demand for transport on such days.\n* **Grid bottlenecks:** When too much wind power pushes from the north to the south, the capacities of the transmission grid are often insufficient. In such cases, generation must be curtailed and energy in the south has to be obtained in other, often fossil, ways.",
        "Abt_Sec4_Title": "4. What is the goal of this simulation?",
        "Abt_Sec4_Info": "Your task is to optimize the **Grid Performance Score**. It evaluates how well your power grid uses renewable energies, avoids line overloads, and limits additional expansion.",
        "Abt_Sec4_Sub1": " Protect Power Lines",
        "Abt_Sec4_Text1": "No line may be loaded above 100%, otherwise power outages may occur.",
        "Abt_Sec4_Sub2": " Minimize Curtailment",
        "Abt_Sec4_Text2": "Prevent clean wind and solar power from having to be thrown away (curtailed) because the grid is full.",
        "Abt_Sec4_Sub3": " No unnecessary expansion",
        "Abt_Sec4_Text3": "Try to build your grid as efficiently as possible. If you add too much capacity that isn't used, the efficiency of your grid decreases.",
        "Abt_Sec5_Title": "5. How does the load flow calculation work?",
        "Abt_Sec5_Sub1": "### DC Load Flow Model",
        "Abt_Sec5_Text1": "For the simplified calculation of the power flow in the grid, we use a DC load flow model. The following simplifying assumptions apply:",
        "Abt_Sec5_List1": "**1. Voltage magnitudes are approximately constant:**",
        "Abt_Sec5_List2": "**2. Line resistances are neglected compared to reactance:**",
        "Abt_Sec5_List3": "**3. The angle differences between the nodes are small:**",
        "Abt_Sec5_List4": "**4. Only active power is considered.**",
        "Abt_Sec5_Sub2": "### Power flow between two nodes",
        "Abt_Sec5_Text2": "Under these assumptions, the active power flow on a line between nodes $a$ and $b$ can be approximately calculated as:",
        "Abt_Sec5_Text3": "Here $\\theta_a$ and $\\theta_b$ are the voltage angles of the two nodes and $x_{ab}$ is the line reactance in per unit.",
        "Abt_Sec5_Text4": "Alternatively, one can write with the conductance factor:",
        "Abt_Sec5_Sub3": "### Node Equation",
        "Abt_Sec5_Text5": "For a node $m$, the total power flow is the sum of the power flows to all connected neighboring nodes:",
        "Abt_Sec5_Text6": "Here $N(m)$ denotes the set of neighboring nodes of $m$. The equations of all nodes can then be written as a linear system of equations in matrix form.",
        "Abt_Expander": "Example calculation: DC load flow with 3 nodes",
        "Abt_Exp_Sub1": "### 1. Inputs",
        "Abt_Exp_Text1": "We consider a simplified grid with three nodes $i$, $j$, and $k$. Nodes $i$ and $j$ inject power, while node $k$ absorbs power.",
        "Abt_Exp_Caption": "Three-node grid for the example calculation",
        "Abt_Exp_Text2": "For the per-unit calculation, the base quantities are first determined:",
        "Abt_Exp_Text3": "This results in the base impedance:",
        "Abt_Exp_Text4": "The injected or absorbed powers are:",
        "Abt_Exp_Text5": "The grid is balanced because:",
        "Abt_Exp_Text6": "The line reactances are:",
        "Abt_Exp_Text7": "These are converted into per unit using the base impedance:",
        "Abt_Exp_Sub2": "### 2. Reduced Equation",
        "Abt_Exp_Text8": "In order for the angles to be uniquely determined, one node is chosen as the reference node. Here we set:",
        "Abt_Exp_Text9": "The node equations for the remaining unknown angles $\\theta_i$ and $\\theta_j$ result in:",
        "Abt_Exp_Text10": "The right side contains the injected or absorbed power in per unit.",
        "Abt_Exp_Text11": "By solving the linear system of equations, one obtains:",
        "Abt_Exp_Sub3": "### 3. Results",
        "Abt_Exp_Text12": "The power flows on the lines are first calculated in per unit and then converted to MW.",
        "Abt_Exp_Text13": "**Line from i to j:**",
        "Abt_Exp_Text14": "**Line from i to k:**",
        "Abt_Exp_Text15": "**Line from j to k:**",
        "Abt_Exp_Text16": "This means a total of 800 MW flows to node $k$. In addition, 100 MW flow from node $i$ to node $j$.",
        "Abt_Exp_Success": "Interpretation: The main transport takes place from the injecting nodes i and j to the consumer node k. In addition, 100 MW flow from i to j because the node voltage angles are different.",
        "Abt_End_Success": "You now know the most important basics of the used grid model.",
        "Abt_Link_Tut": "To the interactive tutorial",
        "Abt_Link_Sim": "Directly to the simulator"
    }
}

#reload erzwingen
