

TXT = {
    "DE": {
        "title": "Deutschland-Netzkarte",
        "slider_wind": "Wind [% der SMARD-Orientierung]",
        "btn_save": "Speichern & Berechnen",
        "status_ok": "Szenario bewältigt.",
        "Wind_node_chosen" : "Du bearbeitest den Wind-Knoten mit der ID:{}",
        "load_node_chosen": "Du bearbeitest den Last-Knoten mit der ID:{}",
        "lokal_slider_wind": "Lokale Wind-Erzeugung [%]",
        "lokal_slider_load":"Lokale Energie verbrauch[%]",
        "Speicher_Knopf_wind": "Speichern & Berechnen",
        "Abbruch_Knopf_wind": "Abbrechen",
        "Stellgrößen": "Stellgrößen",
        "Seitentitel": "Deutschland-Netzkarte: SMARD + DC-Lastfluss",
        "neu_hier_txt": "👋 Neu im Simulator? Lerne die Grundlagen der Netzbalance in unserem Tutorial.",
        "Tutorial_Knopf": "Zum Tutorial",
        "Website_Title": "Deutschland-Netzkarte: SMARD-API, regelbare Restleistung und DC-Lastfluss",
        "Website_Untertitel": "SMARD wird nur für Netzlast, Wind und PV genutzt. Externe Importe/Exporte und SMARD-Restkategorien werden nicht geladen. Die restlichen Erzeuger werden künstlich als konventionelle Erzeuger netzstützend modelliert.",
        "Sprache": "Sprache",
        "Aufgabe": "Aufgabe",
        "Datenquelle": "Datenquelle",
        "SMARD_Datum": "SMARD-Datum",
        "help_Tag": "Sehr aktuelle Tage können noch unvollständige SMARD-Daten haben.",
        "wind_slider":"Wind [% der SMARD-Werte]",
        "pv_slider": "PV [% der SMARD-Werte]",
        "batterie_slider":"BESS Leistung/Energie [%]",
        "soc_slider":"BESS Start-SOC [%]",
        "titel_EE":"Netzmaßnahmen",
        "slider_Netz":"Leitungskapazität / Netzausbau [%]",
        "Szenario_bewaeltigt." : "Szenario bewältigt.",
        "Szenario_nicht_bewältigt." : "Szenario noch nicht bewältigt.",
        "24h_EE_Anteil":"24h EE-Anteil [%]",
        "max_Auslastung_24h":"max. Auslastung 24h [%]",
        "Stunden_Überlast" : "Stunden mit Überlast",
        "Warnung_GPS_ueberlast":"Der Grid Performance Score wurde stark reduziert, weil im Tagesverlauf mindestens eine Leitung über 100 % ausgelastet ist.",
        "Guter_GPS" : "Hoher Grid Performance Score: hoher EE-Anteil ohne Leitungsüberlast.",
        "Mittel_GPS":"Mittlerer Grid Performance Score: technisch brauchbar, aber EE-Anteil oder Netzbelastung sind nicht optimal.",
        "Niedrig_GPS":"Niedriger Grid Performance Score: geringe technische Güte durch niedrigen EE-Anteil oder Netzüberlast.",
        "Netzkarte" : "Netzkarte",
        "Stunde_des_Tages":"Stunde des Tages",
        "Leitungsauslastung" : "Leitungsauslastung",
        "Dispatch" : "Dispatch: (teilweise skalierte) SMARD-Last/Wind/PV + künstlich geregelte restliche Erzeuger",
        "Modellannahmen" : "Modellannahmen",
        "Zielgroeße":"- Zielgröße ist die SMARD-Netzlast.\n",
        "Windgroeße":"- Wind = SMARD Wind Offshore + Wind Onshore.\n",
        "PVgroeße":"- PV = SMARD Photovoltaik.\n",
        "konvgroeße":"- Restliche Erzeuger werden nicht aus SMARD geladen, sondern künstlich auf die Residuallast gefahren.\n",
        "Extgroeßen":"- Externe Importe, Exporte und kommerzielle Austauschflüsse werden nicht geladen.\n",
        "BESSgroeßen":"- BESS: positiv = Entladung, negativ = Ladung.\n",
        "Leitunggroeßen":"- Leitungsauslastung: DC-Loadflow-Näherung, kein vollständiger AC-Lastfluss.",
    },
    "EN": {
        "title": "Germany Grid Map",
        "slider_wind": "Wind [% of SMARD reference]",
        "btn_save": "Save & Calculate",
        "status_ok": "Scenario solved.",
        "Wind_node_chosen" : "You are currently changing the wind node having ID:{}",
        "load_node_chosen": "You are currently changing the load node having ID:{}",
        "lokal_slider_wind": "Lokal wind energy generation[%]",
        "lokal_slider_load":"Lokal energy consumption[%]",
        "Speicher_Knopf_wind": "Save & Calculate",
        "Abbruch_Knopf_wind": "Abort",
        "Stellgrößen": "Adjustable values",
        "Seitentitel": "German grid map: SMARD + DC-Loadflow",
        "neu_hier_txt": "👋 First time in this Simulator? Learn the basics of grid balance in our tutorial.",
        "Tutorial_Knopf": "Go to the tutorial",
        "Website_Title": "German grid map: SMARD-API, adjustable konventional power and DC-Loadflow",
        "Website_Untertitel": "SMARD is just used for the load, wind and PV. Extern Imports/Exports and remaining SMARD-kategories are not used. The remaining power plants are artificially modelled as conventionel power plants which support the network",
        "Sprache": "Language",
        "Aufgabe": "Exercise",
        "Datenquelle": "Data source",
        "SMARD_Datum": "SMARD-Date",
        "help_Tag": "Data for very recent days may still be incomplete in SMARD.",
        "wind_slider":"wind [% of the SMARD-Value]",
        "pv_slider": "PV [% of the SMARD-Value]",
        "batterie_slider":"BESS Power/Energiy [%]",
        "soc_slider":"BESS start-SOC [%]",
        "titel_EE":"Grid measures",
        "slider_Netz":"Conductor capacity / grid expansion [%]",
        "Szenario_bewaeltigt." : "Scenario Completed.",
        "Szenario_nicht_bewältigt." : "Scenario not yet resolved.",
        "24h_EE_Anteil":"24h RE-share [%]",
        "max_Auslastung_24h":"max. utilization 24h [%]",
        "Stunden_Überlast" : "Hours with overload",
        "Warnung_GPS_ueberlast":"The Grid Performance Score has been significantly reduced because at least one line is operating at over 100% capacity at some point during the day.",
        "Guter_GPS" : "High Grid Performance Score: high share of renewable energy without overloading the grid.",
        "Mittel_GPS":"Average Grid Performance Score: technically acceptable, but the share of renewable energy or grid load is not optimal.",
        "Niedrig_GPS":"Low Grid Performance Score: poor technical quality due to a low share of renewable energy or grid overload.",
        "Netzkarte" : "Grid Map",
        "Stunde_des_Tages":"Time of Day",
        "Leitungsauslastung" : "Line Utilization",
        "Dispatch" : "Dispatch: (partially scaled) SMARD load/wind/PV + artificially controlled remaining generators",
        "Modellannahmen" : "Model Assumptions",
        "Zielgroeße":"- The target value is the SMARD grid load.\n",
        "Windgroeße":"- Wind = SMARD Wind Offshore + Wind Onshore.\n",
        "PVgroeße":"- PV = SMARD Photovoltaics.\n",
        "konvgroeße":"- The remaining generators are not loaded from SMARD but are manually set to the residual load.\n",
        "Extgroeßen":"- External imports, exports, and commercial trade flows are not loaded.\n",
        "BESSgroeßen":"- BESS: positive = discharge, negative = charge.\n",
        "Leitunggroeßen":"- Line load: DC load flow approximation; no full AC load flow.",
    }
}
