

TXT = {
    "DE": {
        "title": "Deutschland-Netzkarte",
        "slider_wind": "Wind [% der SMARD-Orientierung]",
        "btn_save": "Speichern & Berechnen",
        "status_ok": "Szenario bewältigt.",
        "Wind_node_chosen" : "Du bearbeitest den Wind-Knoten mit der ID:{}",
        "lokal_slider_wind": "Lokale Wind-Erzeugung [%]",
        "Speicher_Knopf_wind": "Speichern & Berechnen",
        "Abbruch_Knopf_wind": "Abbrechen",
        "Stellgrößen": "Stellgrößen",
        "Seitentitel": "Deutschland-Netzkarte: SMARD + DC-Lastfluss",
        "neu_hier_txt": "👋 Neu im Simulator? Lerne die Grundlagen der Netzbalance in unserem Tutorial.",
        "Tutorial_Knopf": "Zum Tutorial",
        "Website_Title": "Deutschland-Netzkarte: SMARD-API, regelbare Restleistung und DC-Lastfluss",
        "Website_Untertitel": "SMARD wird nur für Netzlast, Wind und PV genutzt. Externe Importe/Exporte und SMARD-Restkategorien werden nicht geladen. Die restlichen Erzeuger werden künstlich als konventionelle Erzeuger netzstützend modelliert.",
        "Aufgabe": "Aufgabe",
        "Datenquelle": "Datenquelle",
        "SMARD_Datum": "SMARD-Datum",
        "wind_slider":"Wind [% der SMARD-Werte]",
        "pv_slider": "PV [% der SMARD-Werte]",
        "batterie_slider":"BESS Leistung/Energie [%]",
        "soc_slider":"BESS Start-SOC [%]",
        "titel_EE":"Netzmaßnahmen",
        "slider_Netz":"Leitungskapazität / Netzausbau [%]"
    },
    "EN": {
        "title": "Germany Grid Map",
        "slider_wind": "Wind [% of SMARD reference]",
        "btn_save": "Save & Calculate",
        "status_ok": "Scenario solved.",
        "Wind_node_chosen" : "You are currently changing the wind node having ID:{}",
        "lokal_slider_wind": "Lokal wind energy generation[%]",
        "Speicher_Knopf_wind": "Save & Calculate",
        "Abbruch_Knopf_wind": "Abort",
        "Stellgrößen": "Adjustable values",
        "Seitentitel": "German grid map: SMARD + DC-Loadflow",
        "neu_hier_txt": "👋 First time in this Simulator? Learn the basics of grid balance in our tutorial.",
        "Tutorial_Knopf": "Go to the tutorial",
        "Website_Title": "German grid map: SMARD-API, adjustable konventional power and DC-Loadflow",
        "Website_Untertitel": "SMARD is just used for the load, wind and PV. Extern Imports/Exports and remaining SMARD-kategories are not used. The remaining power plants are artificially modelled as conventionel power plants which support the network",
        "Aufgabe": "Exercise",
        "Datenquelle": "Data source",
        "SMARD_Datum": "SMARD-Date",
        "wind_slider":"wind [% of the SMARD-Value]",
        "pv_slider": "PV [% of the SMARD-Value]",
        "batterie_slider":"BESS Power/Energiy [%]",
        "soc_slider":"BESS start-SOC [%]",
        "titel_EE":"Grid measures",
        "slider_Netz":"Conductor capacity / grid expansion [%]"
    }
}
